# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # every six hours
    - cron: "0 0,6,12,18 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Prepare data
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm run preparedataP
      - name: run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DEBUG: "False"
          OWNER_ID: ${{ secrets.OWNER_ID }}
        run: npm run start
